FROM ruby:3.2.2

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo

# Node.js（v18）と npm をインストール
RUN apt-get update -qq && \
    apt-get install -y curl gnupg build-essential libpq-dev libssl-dev && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# Bundler
RUN gem install bundler -v "~> 2.4"

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000